name: Build
description: Build the Java project

inputs:
  java_version:
    description: 'The java version to use'
    default: '17'
  java_distribution:
    description: 'The java distribution to use'
    default: 'zulu'
  maven_version:
    description: 'The maven version to use'
    default: '3.8.3'
  maven_flag:
    description: 'The maven flag to use'
    default: '-T 4C -B --no-transfer-progress'
  token:
    description: 'The GitHub token'
    required: true
  publish_artifacts:
    description: 'Publish the artifacts'
    default: 'false'
  ref:
    description: 'The ref to build'
    default: "${{ github.ref }}"
    required: false
  tag_name_prefix:
    description: 'Tag name prefix to be used for checkout'
    default: ''
  aws_role_arn:
    description: 'The Amazon Resource Name (ARN) of the role to assume. This is required for s3 cache'
    default: ''
    required: false
  versioning_strategy:
    description: 'Versioning strategy: manual (Maven-based) or trunk (automated)'
    default: 'manual'
    required: false

outputs:
  version:
    description: 'The version of the artifact'
    value: ${{ steps.set-version.outputs.version }}

runs:
  using: 'composite'
  steps:
    - name: Setup Data Collection
      uses: cleartax/github-actions-metrics@main
      continue-on-error: true
      with:
        data_platform_endpoint: 'https://app-dev-http.clear.in/api/analytics/events'
        build_cache_enabled: ${{ inputs.aws_role_arn != '' }}
        
    - name: Set up JDK ${{ inputs.java_version }}
      uses: actions/setup-java@v4
      with:
        java-version: ${{ inputs.java_version }}
        server-id: github
        distribution: ${{ inputs.java_distribution }}
    
    - name: Configure AWS Credentials for s3 cache
      if: ${{ inputs.aws_role_arn != '' }}
      uses: aws-actions/configure-aws-credentials@v5.0.0
      with:
        aws-region: ap-south-1
        role-to-assume: ${{ inputs.aws_role_arn }}
        
    - name: Cache Maven repository (S3)
      uses: runs-on/cache@v4
      if: ${{ inputs.aws_role_arn != '' }}
      env:
        AWS_REGION: ap-south-1
        RUNS_ON_S3_BUCKET_CACHE: "ct-github-action-cache"
      with:
        path: ~/.m2/repository
        key: ${{ runner.os }}-maven
        restore-keys: |
          ${{ runner.os }}-maven
    
    - name: Cache local Maven repository
      uses: actions/cache@v4
      if: ${{ inputs.aws_role_arn == '' }}
      with:
        path: ~/.m2/repository
        key: ${{ runner.os }}-maven
        restore-keys: |
          ${{ runner.os }}-maven
    
    - name: Set up Maven
      uses: stCarolas/setup-maven@v5
      with:
        maven-version: ${{ inputs.maven_version }}
    
    - name: Setup Git Config
      run: |
          git config --global user.email "clearci@cleartax.in"
          git config --global user.name "clearci"
      shell: bash

    - name: Check the source ref
      id: ref
      env: 
          HOTFIX: ${{ contains( inputs.ref, 'hotfix/') }}
          MASTER: ${{ inputs.ref == 'refs/heads/master' || inputs.ref == 'refs/heads/main' }}
      run: |
          echo "hotfix=$HOTFIX" >> $GITHUB_OUTPUT
          echo "master=$MASTER" >> $GITHUB_OUTPUT
      shell: bash
    
    - name: Set Version (Manual Strategy)
      id: set-version-manual
      if: ${{ inputs.versioning_strategy == 'manual' }}
      run: |
        if [[ "${{ steps.ref.outputs.master }}" == "true" ]]; then
            VERSION=$(mvn ${{inputs.maven_flag}} --non-recursive -q \
              build-helper:parse-version  exec:exec \
              -Dexec.executable=echo \
              -Dexec.args='${parsedVersion.majorVersion}.${parsedVersion.nextMinorVersion}.0') || {
            	echo "Failed to generate version for master branch\n${VERSION}"
            	exit 1
            }
        elif [[ "${{ steps.ref.outputs.hotfix }}" == "true" ]]; then 
            QUALIFIER=$(mvn ${{inputs.maven_flag}} --non-recursive -q \
              build-helper:parse-version  exec:exec \
              -Dexec.executable=echo -Dexec.args='${parsedVersion.qualifier}') || { 
              echo "Failed to extract qualifier for hotfix branch\n${QUALIFIER}"
              exit 1 
            }	
            if [[ -z "$QUALIFIER" ]]; then
              mvn ${{inputs.maven_flag}} -q build-helper:parse-version \
                versions:set \
                -DnewVersion=\${parsedVersion.majorVersion}.\${parsedVersion.minorVersion}.\${parsedVersion.nextIncrementalVersion}-SNAPSHOT \
                versions:commit
              mvn ${{inputs.maven_flag}} -q scm:checkin -Dmessage="[ci skip] set snapshot version"
            fi
            VERSION=$(mvn ${{inputs.maven_flag}} help:evaluate -Dexpression=project.version -q -DforceStdout|sed 's/-SNAPSHOT//') || {
              echo "Failed to evaluate project version for hotfix branch\n${VERSION}"
              exit 1
            }
        else
            VERSION="dev-${GITHUB_SHA::8}"
        fi

        if [[ -z "${VERSION// }" ]]; then
          echo "Error: Version string is empty or invalid"
          exit 1
        fi
        echo "version=$VERSION" >> $GITHUB_OUTPUT
      shell: bash
      env:
        GITHUB_TOKEN: ${{ inputs.token }}
        GITHUB_ACTOR: clearci

    - name: Set Version (Trunk Strategy)
      id: set-version-trunk
      if: ${{ inputs.versioning_strategy == 'trunk' }}
      run: |
        if [[ "${{ steps.ref.outputs.master }}" == "true" || "${{ steps.ref.outputs.hotfix }}" == "true" ]]; then
            echo "Getting version from ClearTax/get-next-version-action"
        else
            VERSION="dev-${GITHUB_SHA::8}"
            echo "version=$VERSION" >> $GITHUB_OUTPUT
        fi
      shell: bash

    - name: Get Next Version (Trunk Strategy - Master/Hotfix)
      id: get-next-version
      if: ${{ inputs.versioning_strategy == 'trunk' && (steps.ref.outputs.master == 'true' || steps.ref.outputs.hotfix == 'true') }}
      uses: ClearTax/get-next-version-action@main
      with:
        repo-token: ${{ inputs.token }}

    - name: Set Version Output
      id: set-version
      run: |
        if [[ "${{ inputs.versioning_strategy }}" == "manual" ]]; then
          VERSION="${{ steps.set-version-manual.outputs.version }}"
        else
          if [[ "${{ steps.ref.outputs.master }}" == "true" || "${{ steps.ref.outputs.hotfix }}" == "true" ]]; then
            VERSION="${{ steps.get-next-version.outputs.version }}"
          else
            VERSION="${{ steps.set-version-trunk.outputs.version }}"
          fi
        fi
        echo "version=$VERSION" >> $GITHUB_OUTPUT
        echo "## Version: $VERSION" >> $GITHUB_STEP_SUMMARY
      shell: bash
    
    - name: Build for production release
      if: ${{ steps.ref.outputs.master == 'true' || steps.ref.outputs.hotfix == 'true' }}
      env:
        GITHUB_TOKEN: ${{ inputs.token }}
        GITHUB_ACTOR: clearci
      run: |
        mvn -DskipTests ${{inputs.maven_flag}} -Darguments=-DskipTests \
         -Dorg.slf4j.simpleLogger.showDateTime=true -Dorg.slf4j.simpleLogger.dateTimeFormat=HH:mm:ss,SSS \
          release:clean release:prepare \
          -DtagNameFormat="v@{project.version}" \
          -DscmCommentPrefix="[ci skip] " \
          -DreleaseVersion=${{ steps.set-version.outputs.version }} \
          -Dusername=clearci -Dpassword=${{ inputs.token }}
      shell: bash

    - name: Build for dev release
      env:
        GITHUB_TOKEN: ${{ inputs.token }}
        GITHUB_ACTOR: clearci
      if: ${{ steps.ref.outputs.master == 'false' && steps.ref.outputs.hotfix == 'false' }}
      run: mvn -DskipTests -Dorg.slf4j.simpleLogger.showDateTime=true -Dorg.slf4j.simpleLogger.dateTimeFormat=HH:mm:ss,SSS ${{inputs.maven_flag}} package
      shell: bash

    - name: Deploy Artifacts to Production
      if: ${{ ( steps.ref.outputs.master == 'true' || steps.ref.outputs.hotfix == 'true' ) && inputs.publish_artifacts == 'true' }}
      env:
        GITHUB_TOKEN: ${{ inputs.token }}
        GITHUB_ACTOR: clearci
      run: |
        git checkout ${{ inputs.tag_name_prefix }}${{ steps.set-version.outputs.version }}
        mvn -fn deploy --settings ./.mvn/settings.xml -T 4C -DskipTests --file pom.xml
      shell: bash

    - name: Upload artifacts 
      uses: 'actions/upload-artifact@v4'
      with:
        name: artifacts-${{github.run_id}}
        path: |
          ${{ github.workspace }}/**/*.jar
        retention-days: 1
    - name: Create release
      if: if: ${{ inputs.versioning_strategy == 'trunk' }}
      uses: cleartax/composite-workflows/semantic-release@main
      with:
          skip-release-pr: true
          token: ${{ inputs.token }}
