name: Build
description: Build the Java project

inputs:
  java_version:
    description: 'The java version to use'
    default: '17'
  java_distribution:
    description: 'The java distribution to use'
    default: 'zulu'
  maven_version:
    description: 'The maven version to use'
    default: '3.8.3'
  maven_flag:
    description: 'The maven flag to use'
    default: '-T 4C -B --no-transfer-progress'
  token:
    description: 'The GitHub token'
    required: true
  publish_artifacts:
    description: 'Publish the artifacts'
    default: 'false'

runs:
  using: 'composite'
  steps:
    - name: Set up JDK ${{ inputs.java_version }}
      uses: actions/setup-java@v4
      with:
        java-version: ${{ inputs.java_version }}
        server-id: github
        distribution: ${{ inputs.java_distribution }}
    - name: Cache local Maven repository
      uses: actions/cache@v4
      with:
        path: ~/.m2/repository
        key: ${{ runner.os }}-maven
        restore-keys: |
          ${{ runner.os }}-maven
    - name: Set up Maven
      uses: stCarolas/setup-maven@v5
      with:
        maven-version: ${{ inputs.maven_version }}

    - name: Build Project
      env:
        GITHUB_TOKEN: ${{ inputs.token }}
        GITHUB_ACTOR: clearci
      run: mvn -DskipTests ${{inputs.maven_flag}} package
      shell: bash

    - name: Deploy Artifacts to Production
      if: ${{ inputs.publish_artifacts == 'true' }}
      env:
        GITHUB_TOKEN: ${{ inputs.token }}
        GITHUB_ACTOR: clearci
      run: |
        mvn -fn deploy --settings ./.mvn/settings.xml -T 4C -DskipTests --file pom.xml

      shell: bash

    - name: Upload artifacts 
      uses: 'actions/upload-artifact@v4'
      with:
        name: artifacts-${{github.run_id}}
        path: |
          ${{ github.workspace }}/**/*.jar
        retention-days: 1
